import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import 'swiper/scss';
import 'swiper/scss/navigation';
import 'swiper/scss/pagination';

import './globals.scss';

const montserrat = Montserrat({
  weight: ['400', '700', '600', '500', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: '301 App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
